### ISSUE TITLE
Portuguese have Caravel as secondary Unique Unit, but it doesn't show up in their tech tree.

### ISSUE THREAD

**Issue by NewCompte** [HSZemi/aoe2techtree#2]
see https://github.com/HSZemi/aoe2techtree/blob/950a394a0f82a8122290705e5a7182f1f37cc057/js/civs.js#L205 and https://aoe2techtree.net/#Portuguese

**Comment by HSZemi** [comment]
What an oversight, thank you!

**Comment by HSZemi** [comment]
What an oversight, thank you! I have fixed the issue.
