### ISSUE TITLE
Siege Tower is absent from the tech tree

### ISSUE THREAD

**Issue by NewCompte** [HSZemi/aoe2techtree#4]
Siege Tower is absent from the tech tree.

You already have the unit image:
https://aoe2techtree.net/img/Units/siege_tower.png
and the description:
https://github.com/HSZemi/aoe2techtree/blob/master/data/data.json#L200

I guess you just need to add it there:
https://github.com/HSZemi/aoe2techtree/blob/master/js/techtree.js#L504
and something like here:
https://github.com/HSZemi/aoe2techtree/blob/master/js/techtree.js#L686

**Comment by HSZemi** [comment]
Oh my, how embarrassing. Thank you for your very detailed bug report! I have added the Siege Tower, the fixed version should be live already.
